name: Bump Version React Native

on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      versionCode:
        required: true
        description: 'GitHub run number'
        type: number
    secrets:
      WORKFLOW_GIT_ACCESS_TOKEN:
        required: true
jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ inputs.repository }}
          token: ${{ secrets.WORKFLOW_GIT_ACCESS_TOKEN }}
      - name: bump version number
        env:
          ref: ${{ github.ref_name }}
          repository: ${{ inputs.repository }}
        run: |

          current_version=$(perl -ne 'print "$1" if /"version":\s*"(.*?)"/' package.json)
          current_version_code=${{ inputs.versionCode }}
          ((current_version_code++))
          perl -i -pe 's/"versionCode":\s*'$(($current_version_code-1))'/"versionCode": '$current_version_code'/' package.json

          echo "Versão atualizada para $new_version (código $current_version_code)"

      - name: GIT commit and push all changed files
        env:
          CI_COMMIT_USER: ${{ github.actor }}
        run: |
          git config --global user.name "${{ env.CI_COMMIT_USER }}"
          git config --global user.email "${{ env.CI_COMMIT_USER }}@users.noreply.github.com"
          git commit -a -m "bump version from ${{ env.old_version }} to ${{ env.new_version}}"
          git push
