name: Github App

on:
  workflow_call:
    secrets:
        app_id:
          required: true
        private_key:
          required: true
jobs:
  next_js_ci:
    name: Run Next.js / React.js CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: get jwt
        run: |
          token=$(./lib/github-app-token.sh)
          echo $token
          echo "token=$token" >> $GITHUB_OUTPUT
        env:
            APP_ID: ${{ secrets.app_id }}
            APP_PRIVATE_KEY: ${{ secrets.private_key }}
      
      